<?php

/**
* restClient para formularios - redmine
*/

// This file is generated by Composer
require_once 'vendor/autoload.php';


$client = new Redmine\Client('http://localhost:8081/redmine', '0a3a5182b5463663dd04db6f5cc5fc60a161286a');
$post = $_POST;

$description  = "Nombre de quien hace la solicitud: ".$post['nombre']."\n";
$description .= "Teléfono de Contacto: ".$post['telefono']."\n";
$description .= "Correo del solicitante: ".$post['email']."\n";
$description .= "Lugar: ".$post['lugar']."\n"."\n";

$description .= "Observaciones: ".$post['observaciones']."\n";


$result = $client->api('issue')->create(array(
		    'project_id'  => $post['project_id'],
		    'subject'     => 'Nueva solicitud de punto de red',
		    'description' => $description,
		    'assigned_to_id' => $post['user_id'],
			));

echo "success \n".$result;
die();

?>''