<?php

/**
* restClient para formularios - redmine
*/

// This file is generated by Composer
require_once 'vendor/autoload.php';


$client = new Redmine\Client('http://localhost:8081/redmine', '0a3a5182b5463663dd04db6f5cc5fc60a161286a');
$post = $_POST;

$description  = "Nombre del evento: ".$post['nombre_evento']."\n"."\n";
$description .= "Descripción: ".$post['descripcion']."\n";
$description .= "Tipo de evento: ".$post['tipo']."\n";
$description .= "Otro tipo de evento: ".$post['otro_evento']."\n"."\n";

$description .= "Correo del solicitante: ".$post['email']."\n";
$description .= "Nombre del solicitante: ".$post['nombre']."\n";
$description .= "Teléfono: ".$post['telefono']."\n";
$description .= "Dependencia: ".$post['dependencia']."\n";
$description .= "Fecha del evento:: ".$post['fecha']."\n";
$description .= "Hora del evento: ".$post['hora']."\n"."\n";

$description .= "Lugar del evento: ".$post['lugar']."\n";
$description .= "Costo del evento: ".$post['costo']."\n";


$result = $client->api('issue')->create(array(
		    'project_id'  => $post['project_id'],
		    'subject'     => 'Nueva solicitud: Difusión de información en redes sociales',
		    'description' => $description,
		    'assigned_to_id' => $post['user_id'],
			));

echo "success \n".$result;
die();

?>