<?php

/**
* restClient para formularios - redmine
*/

// This file is generated by Composer
require_once 'vendor/autoload.php';


$client = new Redmine\Client('http://redmine.utp.edu.co', '5689744759aa3d51ef3eabe1977dd6b5ead85c98');
$post = $_POST;

$description  = "Dependencia: ".$post['nombre']."\n";
$description .= "Nombre del solicitante: ".$post['nombre']."\n";
$description .= "Telefono: ".$post['telefono']."\n";
$description .= "Email: ".$post['email']."\n";
$description .= "----------------------------------------\n";
$description .= "Observaciones \n".$post['observaciones']."\n";
$description .= "----------------------------------------\n";

$result = $client->api('issue')->create(array(
		    'project_id'  => $post['project_id'],
		    'subject'     => 'Nueva solicitud de '.$post['subject'],
		    'description' => $description,
		    'assigned_to_id' => $post['user_id'],
			));

echo "<h2>Su solicitud ha sido enviada </h2><br/> Pronto será contactado a través de correo elecrónico. \n";

echo "<br/>";

?>