
<?php 

// This file is generated by Composer
require_once 'vendor/autoload.php';

$client = new Redmine\Client('http://127.0.0.1:8081/redmine', '0a3a5182b5463663dd04db6f5cc5fc60a161286a');

# CONFIGURACIONES INICIALES

// ----------------------------
// [OPTIONAL] set the port
// (it will try to guess it from the url)
$client->setPort(8081);


$result = $client->api('issue')->update(2,
	array(
    // 'subject'        => 'test note (xml) 1',
    'notes'          => 'probando probando pazu jhesg	',
    'assigned_to_id' => 1,
    'status_id'      => 2,
    //'status'         => 'Resolved',
    'priority_id'    => 5,
    'due_date'       => date('Y-m-d'),
	));

/*
$result = $client->api('issue')->create(array(
    'project_id'  => 'web',
    'subject'     => 'some subject hey pazu',
    'description' => 'a long description blablabla',
    'assigned_to_id' => 'pazu',
));
$client->api('issue')->create(array(
    'project_id'     => 'test',
    'subject'        => 'test api (xml) 3',
    'description'    => 'test api',
    'assigned_to_id' => 3,
));

*/
var_dump($result);
?>
